name = "acro-routine-builder-share"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[kv_namespaces]]
binding = "ARB_SHARES"
id = "44a63e52be28446dbd2dbbeea040b9a4"

[vars]
ALLOWED_ORIGINS = "https://fragpit.github.io,http://localhost:5173"
